In [1]:
import os
import numpy as np
import pandas as pd
import csv

In [2]:
df = pd.read_csv(r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\train_0.csv', index_col=None, header = None)
print(type(df))
df = df.to_numpy()
print(type(df))
print(df)
print(len(df[0]))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
[[ 97 165  90 ... 212 364   0]
 [ 87 244  88 ... 189 385   0]
 [ 86 197  84 ... 203 422   0]
 ...
 [ 17 201  13 ... 219 371   0]
 [ 61 204  70 ... 227 372   0]
 [ 90 164  76 ... 107 378   0]]
137


Making single csv files and eliminating doubled lines:


In [9]:
def entferne_doppelte_zeilen(input_csv, output_csv):
    """
    Entfernt doppelte Zeilen aus einer CSV-Datei.

    Args:
        input_csv: Pfad zur Eingabe-CSV-Datei.
        output_csv: Pfad zur Ausgabedatei, in die die eindeutigen Zeilen geschrieben werden.
    """
    unique_rows = set()
    with open(input_csv, 'r', newline='', encoding='utf-8') as infile:
        reader = csv.reader(infile)
        # Kopfzeile überspringen
        header = next(reader, None)
        for row in reader:
            # Konvertiere die Zeile in einen String, um sie als Schlüssel in das Set aufzunehmen
            row_str = ','.join(row)
            unique_rows.add(row_str)

    with open(output_csv, 'w', newline='', encoding='utf-8') as outfile:
        writer = csv.writer(outfile)
        # Schreibe die Kopfzeile zurück, falls vorhanden
        #if header:
         #   writer.writerow(header)
        for row_str in unique_rows:
            row = row_str.split(',')
            writer.writerow(row)

# Beispielaufruf
input_file = r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\test_images_0.csv'
output_file = 'test_0.csv'
entferne_doppelte_zeilen(input_file, output_file)

In [ ]:
df6 = pd.read_csv(r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\test_6.csv', header = None)
print(len(df6))
df5 = pd.read_csv(r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\test_5.csv', header = None)
print(len(df5))
df4 = pd.read_csv(r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\test_4.csv', header = None)
print(len(df4))
df3 = pd.read_csv(r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\test_3.csv', header = None)
print(len(df3))
df2 = pd.read_csv(r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\test_2.csv', header = None)
print(len(df2))
df1 = pd.read_csv(r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\test_1.csv', header = None)
print(len(df1))
df0 = pd.read_csv(r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\test_0.csv', header = None)
print(len(df0))
print('Das macht', len(df0)+len(df1)+len(df2)+len(df3)+len(df4)+len(df5)+len(df6), '!')

543
672
905
1354
640
77
643
Das macht 4834 !
     0    1    2    3    4    5    6    7    8    9    ...  127  128  129  \
0     77   48   80   98   92  147  105  194  122  238  ...  248  319  252   
1     40  215   50  272   66  327   83  376  107  421  ...  411  336  408   
2     65  222   62  268   61  315   61  365   70  412  ...  383  290  412   
3     30  214   31  267   40  324   55  374   82  420  ...  422  318  440   
4     57  218   61  272   70  325   83  378  100  427  ...  396  318  421   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
538   18  199   25  255   33  312   47  366   69  416  ...  389  333  394   
539    5  198   12  258   22  315   40  365   73  409  ...  350  302  372   
540   86  235   90  281  100  324  121  363  145  403  ...  366  343  363   
541   88  213   97  256  110  297  124  337  142  373  ...  353  322  361   
542   43  199   47  254   59  311   76  364  100  413  ...  414  312  401   

     130  131  132  133  134  

In [11]:
data = [df0, df1,df2, df3, df4, df5,df6]
df_all = pd.concat(data, axis =0)
print(df_all)

     0    1    2    3    4    5    6    7    8    9    ...  127  128  129  \
0     -3  120   15  193   32  265   55  331   94  390  ...  373  387  360   
1     84  194   86  238   92  282  101  325  116  367  ...  377  309  381   
2     55  130   61  193   69  256   82  316  104  371  ...  355  335  364   
3     27  233   50  298   71  355   97  406  132  452  ...  386  392  378   
4     55  178   53  235   56  293   61  348   76  399  ...  387  316  388   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
538   18  199   25  255   33  312   47  366   69  416  ...  389  333  394   
539    5  198   12  258   22  315   40  365   73  409  ...  350  302  372   
540   86  235   90  281  100  324  121  363  145  403  ...  366  343  363   
541   88  213   97  256  110  297  124  337  142  373  ...  353  322  361   
542   43  199   47  254   59  311   76  364  100  413  ...  414  312  401   

     130  131  132  133  134  135  136  
0    315  452  282  463  254  461 

In [12]:
df_all.to_csv('finaltest.csv', index=False, header = False)

---

Now some facial features based on the extracted facial landmarks shall be designed and determined: 

| Number | facial feature | used landmarks | computation |
| --- | --- | --- | --- | 
| 0 | Mouth distance | 63, 67 | abs(63-67)|
| 1 | Eye area right| 37,38,39,40,41,42 | A(...) |
| 2 | Eye area left | 43,44,45,46,47,48 | A(...) |
| 3 | Mouth area| 49,50,51,52,53,54,55,56,57,58,59,60 | A(...) |
| 4 | Eye eyelash distance right | 37,18,19,38,39,21,40,22 | (1\4)*(abs(37-18)+abs(19-38)+abs(39-21)+abs(40-22))|
| 5 | Eye eyelash distance left| 23,43,44,24,45,26,46,27 | (1\4)*(abs(23-43)+abs(44-24)+abs(45-26)+abs(46-27))|
| 6 | Nose Height| 28,29,30,31,34| abs(28-29)+abs(29-30)+abs(30-31)+abs(31-34) |
| 7 | Nose Width| 32,33,34,35,36 | abs(32-33)+abs(33-34)+abs(34-35)+abs(35-36)|
| 8 | Mouth nose distance| 34, 52| abs(34-52)|
| 9 | Mouth chin distance| 9, 58| abs(9-58)|
| 10 | Head width| 1, 17| abs(1-17)|
| 11 | Mouth area Eye area ratio| | (category(2) + category(3) / category(4))|
| 12 | Left-Right-Eye Ratio| | catgory(5)/category(6)|
| 13 | Mouth-Chin-angle| 49, 9, 55| angle(49, 9, 55)|
| 14 | Eyes-Nose-angle| 37, 34, 46| angle(37, 34, 46)|


---

In [13]:
df = pd.read_csv(r'C:\Users\Maximilian\Documents\Applied in Paython\Emotion-Recognition-from-Facial-Landmarks\finaltest.csv', index_col=None, header = None)
print(type(df))
df = df.to_numpy()
print(type(df))
print(df)
print(len(df[0]))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
[[ -3 120  15 ... 254 461   0]
 [ 84 194  86 ... 234 360   0]
 [ 55 130  61 ... 234 434   0]
 ...
 [ 86 235  90 ... 238 420   6]
 [ 88 213  97 ... 256 376   6]
 [ 43 199  47 ... 243 391   6]]
137


In [14]:
def eucdist(p,q):
    """
    Calculates the euclidean distance.

    Arguments:
    ----------
     p: Numpy Array (first point)
     q: Numpy Array (second point)

    Returns:
    --------
    Euclidean distance between the points. 
    """
    return np.sqrt(np.sum((p-q)**2))



Mouthdistance, No. 0:

In [15]:
ff0_ = []
for i in range(0, len(df)):
    q = np.array([df[i][63*2-2], df[i][63*2-1]])
    p = np.array([df[i][67*2-2], df[i][67*2-1]])
    ff0 = eucdist(q, p)
    ff0_.append(ff0)
ff0_ = pd.DataFrame(ff0_)
print(len(ff0_), ff0_)

4834               0
0     82.000000
1     15.000000
2     83.000000
3     30.805844
4     35.000000
...         ...
4829  12.041595
4830  64.070274
4831  52.345009
4832  22.022716
4833  25.000000

[4834 rows x 1 columns]


Headwidth, No. 10:

In [16]:
ff10_ = []
for i in range(0, len(df)):
    q = np.array([df[i][1*2-2], df[i][1*2-1]])
    p = np.array([df[i][17*2-2], df[i][17*2-1]])
    ff10 = eucdist(q, p)
    ff10_.append(ff10)
ff10_ = pd.DataFrame(ff10_)
print(len(ff10_), ff10_)

4834                0
0     505.284079
1     364.137337
2     420.233269
3     472.969344
4     381.996073
...          ...
4829  430.029069
4830  394.001269
4831  351.647551
4832  374.370138
4833  410.537453

[4834 rows x 1 columns]


Mouth nose distance, No. 8:

In [17]:
ff8_ = []
for k in range(0, len(df)):
    q = np.array([df[k][34*2-2], df[k][34*2-1]])
    p = np.array([df[k][52*2-2], df[k][52*2-1]])
    ff8 = eucdist(q, p)
    ff8_.append(ff8)
ff8_ = pd.DataFrame(ff8_)
print(len(ff8_),ff8_)

4834               0
0     26.305893
1     42.011903
2     24.020824
3     36.359318
4     33.015148
...         ...
4829  59.000000
4830  29.068884
4831  26.248809
4832  37.336309
4833  42.011903

[4834 rows x 1 columns]


Mouth chin distance, No. 9:

In [18]:
ff9_ = []
for k in range(0, len(df)):
    q = np.array([df[k][9*2-2], df[k][9*2-1]])
    p = np.array([df[k][58*2-2], df[k][58*2-1]])
    ff9 = eucdist(q, p)
    ff9_.append(ff9)
ff9_ = pd.DataFrame(ff9_)
print(len(ff9_), ff9_)

4834               0
0     52.354560
1     75.166482
2     57.035077
3     54.129474
4     75.059976
...         ...
4829  73.824115
4830  69.180922
4831  62.936476
4832  57.706152
4833  92.439169

[4834 rows x 1 columns]


Eye eyelash distance right, No. 4:

In [19]:
ff4_ = []
for k in range(0, len(df)):
    q = np.array([df[k][37*2-2], df[k][37*2-1]])
    p = np.array([df[k][18*2-2], df[k][18*2-1]])
    q1 = np.array([df[k][19*2-2], df[k][19*2-1]])
    p1 = np.array([df[k][38*2-2], df[k][38*2-1]])
    q2 = np.array([df[k][39*2-2], df[k][39*2-1]])
    p2 = np.array([df[k][21*2-2], df[k][21*2-1]])
    q3 = np.array([df[k][40*2-2], df[k][40*2-1]])
    p3 = np.array([df[k][22*2-2], df[k][22*2-1]])
    ff4 = 0.25*(eucdist(q, p)+eucdist(q1, p1)+eucdist(q2, p2)+eucdist(q3, p3))
    ff4_.append(ff4)
ff4_ = pd.DataFrame(ff4_)
print(len(ff4_), ff4_)

4834               0
0     51.946708
1     50.712792
2     39.659682
3     56.155777
4     35.927589
...         ...
4829  55.724270
4830  68.161018
4831  49.383968
4832  53.767311
4833  60.368337

[4834 rows x 1 columns]


Eye eyelash distance left, No. 5:

In [20]:
ff5_ = []
for k in range(0, len(df)):
    q = np.array([df[k][23*2-2], df[k][23*2-1]])
    p = np.array([df[k][43*2-2], df[k][43*2-1]])
    q1 = np.array([df[k][44*2-2], df[k][44*2-1]])
    p1 = np.array([df[k][24*2-2], df[k][24*2-1]])
    q2 = np.array([df[k][45*2-2], df[k][45*2-1]])
    p2 = np.array([df[k][26*2-2], df[k][26*2-1]])
    q3 = np.array([df[k][46*2-2], df[k][46*2-1]])
    p3 = np.array([df[k][27*2-2], df[k][27*2-1]])
    ff5 = 0.25*(eucdist(q, p)+eucdist(q1, p1)+eucdist(q2, p2)+eucdist(q3, p3))
    ff5_.append(ff5)
ff5_ = pd.DataFrame(ff5_)
print(len(ff5_), ff5_)

4834               0
0     58.096597
1     48.461249
2     37.357342
3     59.377501
4     34.613154
...         ...
4829  52.144962
4830  62.694956
4831  53.543887
4832  54.636371
4833  59.341091

[4834 rows x 1 columns]


Nose height, No.6:

In [21]:
ff6_ = []
for k in range(0, len(df)):
    q = np.array([df[k][28*2-2], df[k][28*2-1]])
    q1 = np.array([df[k][29*2-2], df[k][29*2-1]])
    q2 = np.array([df[k][30*2-2], df[k][30*2-1]])
    q3 = np.array([df[k][31*2-2], df[k][31*2-1]])
    q4 = np.array([df[k][34*2-2], df[k][34*2-1]])
    ff6 =(eucdist(q, q1)+eucdist(q1, q2)+eucdist(q2, q3)+eucdist(q3, q4))
    ff6_.append(ff6)
ff6_ = pd.DataFrame(ff6_)
print(len(ff6_), ff6_)

4834                0
0     192.634577
1     129.158936
2     145.271817
3     156.197480
4     147.043171
...          ...
4829  154.237741
4830  126.335757
4831  129.880984
4832  110.411160
4833  154.193784

[4834 rows x 1 columns]


Nose width, No.7:

In [22]:
ff7_ = []
for k in range(0, len(df)):
    q = np.array([df[k][32*2-2], df[k][32*2-1]])
    q1 = np.array([df[k][33*2-2], df[k][33*2-1]])
    q2 = np.array([df[k][34*2-2], df[k][34*2-1]])
    q3 = np.array([df[k][35*2-2], df[k][35*2-1]])
    q4 = np.array([df[k][36*2-2], df[k][36*2-1]])
    ff7 =(eucdist(q, q1)+eucdist(q1, q2)+eucdist(q2, q3)+eucdist(q3, q4))
    ff7_.append(ff7)
ff7_ = pd.DataFrame(ff7_)
print(len(ff7_), ff7_)

4834                0
0     129.348283
1      69.865869
2     105.065432
3     115.436728
4      99.508335
...          ...
4829   80.289830
4830   80.420090
4831   81.061477
4832   61.737796
4833   85.639086

[4834 rows x 1 columns]


Shoelace formula for area of a polygon:

In [23]:
def polyarea(vertices):
    """
    Berechnet den Flächeninhalt eines Polygons mit der Shoelace-Formel.

    Args:
        vertices: Eine Liste von Tupeln oder Listen, die die (x, y)-Koordinaten der Eckpunkte des Polygons darstellen.

    Returns:
        Der Flächeninhalt des Polygons.
    """
    n = len(vertices)
    if n < 3:
        return 0  # Ein Polygon benötigt mindestens 3 Eckpunkte

    area = 0.0
    for i in range(n):
        j = (i + 1) % n
        area += vertices[i][0] * vertices[j][1]
        area -= vertices[j][0] * vertices[i][1]
    return abs(area) / 2.0

In [24]:
polyarea([(0,0),(2,0),(2,8)])

8.0

Eye area right, No.1:

In [25]:
ff1_ = []
for k in range(0, len(df)):
    q = (df[k][37*2-2], df[k][37*2-1])
    q1 = (df[k][38*2-2], df[k][38*2-1])
    q2 = (df[k][39*2-2], df[k][39*2-1])
    q3 = (df[k][40*2-2], df[k][40*2-1])
    q4 = (df[k][41*2-2], df[k][41*2-1])
    q5 = (df[k][42*2-2], df[k][42*2-1])
    ff1 = polyarea([q,q1,q2,q3,q4,q5])
    ff1_.append(ff1)
ff1_ = pd.DataFrame(ff1_)
print(len(ff1_), ff1_)

4834            0
0     1291.5
1      876.0
2      633.5
3     1911.5
4     1165.0
...      ...
4829  1867.0
4830  1560.0
4831  1176.0
4832  1650.5
4833  1420.5

[4834 rows x 1 columns]


Eye area left, No.2:

In [26]:
ff2_ = []
for k in range(0, len(df)):
    q = (df[k][43*2-2], df[k][43*2-1])
    q1 = (df[k][44*2-2], df[k][44*2-1])
    q2 = (df[k][45*2-2], df[k][45*2-1])
    q3 = (df[k][46*2-2], df[k][46*2-1])
    q4 = (df[k][47*2-2], df[k][47*2-1])
    q5 = (df[k][48*2-2], df[k][48*2-1])
    ff2 = polyarea([q,q1,q2,q3,q4,q5])
    ff2_.append(ff2)
ff2_ = pd.DataFrame(ff2_)
print(len(ff2_),ff2_)

4834            0
0     1233.5
1      868.5
2      628.0
3     1991.5
4     1144.5
...      ...
4829  1846.5
4830  1378.0
4831  1296.0
4832  1852.5
4833  1350.0

[4834 rows x 1 columns]


Mouth area, No.3:

In [27]:
ff3_ = []
for k in range(0, len(df)):
    q = (df[k][49*2-2], df[k][49*2-1])
    q1 = (df[k][50*2-2], df[k][50*2-1])
    q2 = (df[k][51*2-2], df[k][51*2-1])
    q3 = (df[k][52*2-2], df[k][52*2-1])
    q4 = (df[k][53*2-2], df[k][53*2-1])
    q5 = (df[k][54*2-2], df[k][54*2-1])
    p = (df[k][55*2-2], df[k][55*2-1])
    p1 = (df[k][56*2-2], df[k][56*2-1])
    p2 = (df[k][57*2-2], df[k][57*2-1])
    p3 = (df[k][58*2-2], df[k][58*2-1])
    p4 = (df[k][59*2-2], df[k][59*2-1])
    p5 = (df[k][60*2-2], df[k][60*2-1])
    ff3 = polyarea([q,q1,q2,q3,q4,q5,p,p1,p2,p3,p4,p5])
    ff3_.append(ff3)
ff3_ = pd.DataFrame(ff3_)
print(len(ff3_),ff3_)

4834             0
0     20222.5
1      3393.5
2     13984.0
3     13420.0
4      7926.5
...       ...
4829   7000.0
4830  10321.5
4831  10884.0
4832   4594.5
4833   2645.5

[4834 rows x 1 columns]


In [28]:
ff3_[0][4]

7926.5

Mouth area eye area ratio, No.11:

In [29]:
ff11_ = []
for k in range(0, len(df)):
    ff11_.append((ff1_[0][k] + ff2_[0][k])/ff3_[0][k] )
ff11_ = pd.DataFrame(ff11_)
print (len(ff11_), ff11_)

4834              0
0     0.124861
1     0.514071
2     0.090210
3     0.290835
4     0.291364
...        ...
4829  0.530500
4830  0.284649
4831  0.227122
4832  0.762433
4833  1.047250

[4834 rows x 1 columns]


Left right eye ratio, No.12:

In [30]:
ff12_ = []
for k in range(0, len(df)):
    ff12_.append(ff4_[0][k]/ff5_[0][k])
ff12_ = pd.DataFrame(ff12_)
print (len(ff12_), ff12_)


4834              0
0     0.894144
1     1.046461
2     1.061630
3     0.945742
4     1.037975
...        ...
4829  1.068642
4830  1.087185
4831  0.922308
4832  0.984094
4833  1.017311

[4834 rows x 1 columns]


Determining angles by using the cosine law:

Angle mouth chin, No. 13:

In [31]:
ff13_ = []
for k in range(0, len(df)):
    #Build vectors
    v1 = (df[k][49*2-2]-df[k][9*2-2], df[k][49*2-1]-df[k][9*2-1])
    v2 = (df[k][55*2-2]-df[k][9*2-2], df[k][55*2-1]-df[k][9*2-1])
    #Calculate cosine of the angle:
    cos_al = np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2)) 
    ff13 = np.degrees(np.arccos(cos_al))
    ff13_.append(ff13)
ff13_ = pd.DataFrame(ff13_)
print (len(ff13_), ff13_)

4834               0
0     66.291362
1     74.768404
2     52.745317
3     78.619921
4     61.959363
...         ...
4829  67.955469
4830  56.066344
4831  61.585811
4832  67.590982
4833  59.694543

[4834 rows x 1 columns]


Eyes nose angle, No. 14:

In [32]:
ff14_ = []
for k in range(0, len(df)):
    #Build vectors
    v1 = (df[k][37*2-2]-df[k][34*2-2], df[k][37*2-1]-df[k][34*2-1])
    v2 = (df[k][46*2-2]-df[k][34*2-2], df[k][46*2-1]-df[k][34*2-1])
    #Calculate cosine of the angle:
    cos_al = np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2)) 
    ff14 = np.degrees(np.arccos(cos_al))
    ff14_.append(ff14)
ff14_ = pd.DataFrame(ff14_)
print (len(ff14_), ff14_)

4834               0
0     76.944777
1     87.775568
2     76.391523
3     89.180579
4     78.018463
...         ...
4829  88.035870
4830  91.233527
4831  84.552279
4832  95.208011
4833  76.863705

[4834 rows x 1 columns]


---

Building up the final csv file with all extracted facial features:

In [33]:
classcolumn = pd.DataFrame(df[0:, 136])
data = [ff0_, ff1_,ff2_, ff3_, ff4_, ff5_,ff6_, ff7_, ff8_, ff9_, ff10_, ff11_, ff12_, ff13_, ff14_, classcolumn]
df_all = pd.concat(data, axis =1)
print(df_all)

              0       0       0        0          0          0           0  \
0     82.000000  1291.5  1233.5  20222.5  51.946708  58.096597  192.634577   
1     15.000000   876.0   868.5   3393.5  50.712792  48.461249  129.158936   
2     83.000000   633.5   628.0  13984.0  39.659682  37.357342  145.271817   
3     30.805844  1911.5  1991.5  13420.0  56.155777  59.377501  156.197480   
4     35.000000  1165.0  1144.5   7926.5  35.927589  34.613154  147.043171   
...         ...     ...     ...      ...        ...        ...         ...   
4829  12.041595  1867.0  1846.5   7000.0  55.724270  52.144962  154.237741   
4830  64.070274  1560.0  1378.0  10321.5  68.161018  62.694956  126.335757   
4831  52.345009  1176.0  1296.0  10884.0  49.383968  53.543887  129.880984   
4832  22.022716  1650.5  1852.5   4594.5  53.767311  54.636371  110.411160   
4833  25.000000  1420.5  1350.0   2645.5  60.368337  59.341091  154.193784   

               0          0          0           0         0   

In [34]:
df_all.to_csv('finaltestdata.csv', index=False, header = False) #Generates a file automatically!

---

Now for the test data: